### ISSUE TITLE
Setup bricht ab, wenn DBM nicht im Standard-Pfad installiert ist

### ISSUE THREAD

**Issue by HarakuneSan** [DBM-German/DBM-German-Bot#2]
Wenn man DBM nicht in dem Standert Pfad hat(C:/Program Files (x86)/Steam/steamapps/common/Discord Bot Maker/) schlägt das installationsscript fehl

**To Reproduce**
1. DBM in einem anderen Pfad oder auf einer anderen Festplatte installieren
2. npm `run setup` im geklonten ordner ausführen

**Expected behavior**
Das script läuft durch und erstellt das projekt ohne komplikationen

**Wie ich es gelöst habe**
Ich habe meinen DBM Pfad manuell in den script konstanten geändert

**Comment by TheLeCrafter** [comment]
Soll das Script am Anfang nach dem Installationspfad fragen?

**Comment by ACertainCoder** [comment]
Den Pfad jedes Mal manuell angeben zu müssen, wäre nervig. Steam hat eine Index-Datei mit allen installierten Spielen / Programmen und deren Verzeichnissen. Ich werde versuchen das Skript dahingehend anzupassen, dass es diese Datei checkt.

**Comment by ACertainCoder** [comment]
Dieses Problem sollte durch Commit [#ab17d0a](https://github.com/dbm-german/DBM-German-Bot/commit/ab17d0a37dd41336c932b28626ca4468e2216d96) behoben sein. Bitte gegenprüfen.

**Comment by HarakuneSan** [comment]
Das problem wurde nicht behoben, da ich sogar steam auf einer anderen Platte installiert habe.
Das script könnte ja nur fragen, wenn der pfad nicht gefunden wurde

**Comment by ACertainCoder** [comment]
Mit Commit [f9b5ea3](https://github.com/dbm-german/DBM-German-Bot/commit/f9b5ea39d3941ebf36001c75aa77d834cf4618e2) wird beim Setup auf die Registry zurückgegriffen, um das Steam-Verzeichnis zu finden. Bitte erneut gegenprüfen, ob das Skript nun ordnungsgemäß durchläuft.

**Comment by HarakuneSan** [comment]
Es funktioniert nun einwandfrei

**Comment by ACertainCoder** [comment]
Problem behoben.
